import type { MatchPreview } from "@/lib/types";

const MONO = "'JetBrains Mono',monospace";

interface Props {
  preview: MatchPreview;
}

export default function MatchPreviewCard({ preview }: Props) {
  return (
    <div style={{
      background: "#120F1E",
      border: "1px solid rgba(255,255,255,0.07)",
      borderRadius: 16,
      padding: "20px 24px",
    }}>
      <p style={{ fontSize: 14.5, lineHeight: 1.7, color: "#C8C3D6", margin: 0 }}>
        {preview.preview_text}
      </p>
      <p style={{ fontFamily: MONO, fontSize: 12, color: "#4A4560", marginTop: 14 }}>
        Generated by {preview.model_used}
      </p>
    </div>
  );
}
