import type { MatchPreview } from "@/lib/types";

interface Props {
  preview: MatchPreview;
}

export default function MatchPreviewCard({ preview }: Props) {
  return (
    <section className="rounded-xl border border-slate-700 bg-slate-800/50 p-5">
      <h2 className="mb-3 text-sm font-semibold uppercase tracking-widest text-slate-400">
        Match Preview
      </h2>
      <p className="text-sm leading-relaxed text-slate-200">{preview.preview_text}</p>
      <p className="mt-3 text-xs text-slate-500">
        Generated by {preview.model_used}
      </p>
    </section>
  );
}
