package models

import (
	"encoding/json"
	"time"
)

// TriviaFact is one statistical fact generated by footy/trivia.py.
type TriviaFact struct {
	Template string          `json:"template"`
	Text     string          `json:"text"`
	Data     json.RawMessage `json:"data,omitempty"`
}

// MatchTrivia holds all auto-generated trivia facts for one fixture.
type MatchTrivia struct {
	MatchID     string       `json:"match_id"`
	GeneratedAt time.Time    `json:"generated_at"`
	Facts       []TriviaFact `json:"facts"`
}

// MatchPreview holds the LLM-generated pre-match preview for one fixture.
type MatchPreview struct {
	MatchID     string    `json:"match_id"`
	PreviewText string    `json:"preview_text"`
	ModelUsed   string    `json:"model_used"`
	GeneratedAt time.Time `json:"generated_at"`
}

// TournamentTriviaFact is one computed record or milestone for the whole tournament.
type TournamentTriviaFact struct {
	Category  string `json:"category"`            // "milestone", "record", "hat_trick", "goal", "discipline"
	Icon      string `json:"icon"`                // emoji for UI display
	Headline  string `json:"headline"`
	Detail    string `json:"detail,omitempty"`
	MatchID   string `json:"match_id,omitempty"`
	HomeTeam  string `json:"home_team,omitempty"`
	AwayTeam  string `json:"away_team,omitempty"`
	HomeGoals *int   `json:"home_goals,omitempty"`
	AwayGoals *int   `json:"away_goals,omitempty"`
}

// TournamentTriviaResponse is the response for GET /v1/stats/trivia.
type TournamentTriviaResponse struct {
	Facts      []TournamentTriviaFact `json:"facts"`
	ComputedAt string                 `json:"computed_at"`
}
