-- =============================================================================
-- FootyForecast: Trivia, previews, and leaderboard users
-- Migration: 20260618000000_trivia_previews_users
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Auto-generated trivia facts per fixture
-- ---------------------------------------------------------------------------

CREATE TABLE match_trivia (
    fixture_id   TEXT        NOT NULL REFERENCES fixtures(id),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    facts        JSONB       NOT NULL,
    PRIMARY KEY (fixture_id)
);

COMMENT ON TABLE match_trivia IS
    'Pre-match statistical facts generated by footy/trivia.py. '
    'One row per fixture, overwritten on regeneration. '
    'facts is a JSON array of {template, text, data} objects.';

COMMENT ON COLUMN match_trivia.facts IS
    'Array of fact objects. Each has: '
    '  template: string identifier (e.g. "head_to_head", "form", "streak") '
    '  text: human-readable sentence '
    '  data: structured numbers behind the sentence';


-- ---------------------------------------------------------------------------
-- LLM-generated match previews
-- ---------------------------------------------------------------------------

CREATE TABLE match_previews (
    fixture_id    TEXT        NOT NULL REFERENCES fixtures(id),
    preview_text  TEXT        NOT NULL,
    model_used    TEXT        NOT NULL,
    generated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (fixture_id)
);

COMMENT ON TABLE match_previews IS
    'LLM-generated 2-3 sentence match preview stored pre-kickoff. '
    'Regenerated by footy/previews.py each time model predictions are refreshed. '
    'model_used records the Claude model ID used for auditability.';


-- ---------------------------------------------------------------------------
-- Leaderboard users
-- Lightweight identity: user chooses a handle, stored as user_id.
-- No auth — handle is the identifier. First to use a handle owns it for that
-- fixture (enforced by the UNIQUE constraint on user_predictions).
-- ---------------------------------------------------------------------------

CREATE TABLE leaderboard_users (
    user_id      TEXT        PRIMARY KEY,
    display_name TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE leaderboard_users IS
    'One row per leaderboard participant. user_id = the handle they chose. '
    'display_name is the same value (kept separate for future display customisation). '
    'No passwords or email — this is a light anonymous leaderboard.';
